### ISSUE TITLE
Switch to HTML5

### ISSUE THREAD

**Issue by squiddy** [tobami/codespeed#106]
With the merge of a couple of JS improvements, a commit ebf98733691bd936303fc1e8ab166032fa31110e was merged that makes use HTML5's custom data attributes. My question in the pull request was probably not visible enough, so I'm asking here. Using custom data attributes is only valid in HTML5 (or you could provide a custom DTD, but no one does that I think).

In `base.html` a comment suggests that a switch to HTML5 was considered: https://github.com/tobami/codespeed/blob/master/example/templates/base.html#L18

I don't have any particular feature in mind that **needs** HTML5 (except custom data attributes), but I don't see anything wrong with upgrading.

**Comment by tobami** [comment]
this is no longer current
