### ISSUE TITLE
Sorting benchmarks results sort by alphabetical order, not by value

### ISSUE THREAD

**Issue by mykaul** [tobami/codespeed#140]
See for example, running benchmark, results in 'Bandwidth in MBps'  (clicking on the headers to sort by it).

Benchmark	Bandwidth in MBps	Change	Trend
Average		-2.12%	-8.05%
A-d10-Bandwidth	1042.00	-1.14%	-19.66%
B-50-Bandwidth	1047.00	-0.57%	-5.76%
C-d2-Bandwidth	1053.00	-0.09%	-3.53%
D-Bandwidth	1054.00	-0.09%	-3.08%
E-r-Bandwidth	1055.00	0.00%	-2.99%
F-r-Bandwidth	135.00	0.00%	-2.88%
G-d10-Bandwidth	135.00	0.00%	-2.88%
H-d2-Bandwidth	135.00	0.00%	-2.88%
I-d10-Bandwidth	1407.00	-6.39%	-9.87%

If you look, test 'F-..' comes after tests A to E, then I comes afterwards - although it should have been sorted as:
135, 135, 1042, 1047...

**Comment by tobami** [comment]
Clicking on each column does sort by its contents, be it by value or by name
