### ISSUE TITLE
'Permalink' link does not include baseline

### ISSUE THREAD

**Issue by mykaul** [tobami/codespeed#141]
When clicking on permalink, I'm losing the 'baseline' parameter.
Example:
http://example.com:8080/timeline/?exe=1%2C2&base=2%2B19&ben=4k-256T-r-IOPS&env=1&revs=200&equid=off#/?exe=1,2&base=2+19&ben=4k-256T-r-IOPS&env=5&revs=200&equid=off

The permalink is:
http://example.com:8080/timeline/?exe=1%2C2&base=2%2B19&ben=4k-256T-r-IOPS&env=1&revs=200&equid=off#

**Comment by str4d** [comment]
AFAICT this is working correctly in latest master. @mykaul or @tobami could you test and confirm?

**Comment by tobami** [comment]
It is working on 'master'
