### ISSUE TITLE
github revisions backend not working

### ISSUE THREAD

**Issue by staticfloat** [tobami/codespeed#155]
At first, I had my github url set to http://github.com/JuliaLang/julia.git, but that didn't work because the github API doesn't like the `.git` ending when asking for commits.  Try these two links for a demonstration: [doesn't work](https://api.github.com/repos/JuliaLang/julia.git/git/commits/7eb0ad291baa0000d2d934b32f
61a4d327ae142c), [works](https://api.github.com/repos/JuliaLang/julia/git/commits/7eb0ad291baa0000d2d934b32f
61a4d327ae142c).

Once I had fixed that, I noticed I still get errors in my server logs:
```
RROR:root:Unhandled Exception on request for http://julia-codespeed.csail.mit.edu/changes/logs/?revisionid=46
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/codespeed-0.9.1-py2.7.egg/codespeed/views.py", line 781, in displaylo
gs
    log['commit_browse_url'] = project.commit_browsing_url.format(**log)
KeyError: u'commitid'
```

Since I remembered `commitid` being something the recent github API pull request mentioned, I thought this might be some case that fell through the cracks.  Ideas?

**Comment by tobami** [comment]
It does work as of master
