### ISSUE TITLE
Database accepting results, but UI in broken state

### ISSUE THREAD

**Issue by rrnewton** [tobami/codespeed#178]
We're running [this codespeed instance](http://codespeed.crest.iu.edu/), which is currently based on @tmcdonell's fork of @nomeata's fork of this repo, ghc branch.

All results are going in ok (although we have some sensitivity to the particulars of url encoding the json, and we get an internal error if the Environment is one not already added), but we have the remaining problems with the UI:
- The "recent results" widget was there and now it's gone
- The comparison view showed us some plots at some point, but now doesn't.
- The timeline view never showed a plot for us, and at least some of the time it would not show it would not list Executables that had been added via pushing new Results, even if those Executables were listed in the Comparison tab.

Does this sound familiar to anyone?  Any idea where to start?

**Comment by str4d** [comment]
I encountered what I think was a similar issue when setting up https://speed.z.cash - data was in the database but not being displayed. Setting `DEF_BRANCH` in `settings.py` (below `from codespeed.settings import *`) solved the problem.

**Comment by tobami** [comment]
@str4d #224 should solve this problem for most
