### ISSUE TITLE
does codespeed support python3? Here is a dummy syntax error...

### ISSUE THREAD

**Issue by 5nizza** [tobami/codespeed#197]
In file "codespeed-0.10.1/codespeed/github.py", line 41, which looks like:

    try:
        commit_json = json.load(urllib.urlopen(commit_url))
    except IOError, e:
        logger.exception("Unable to load %s: %s",
                         commit_url, e, exc_info=True)
        raise e

which is not a valid python3..

**Comment by 5nizza** [comment]
Oh, I see, the problem was I downloaded the zip file version, which does not support python3.

**Comment by tobami** [comment]
Yes, Python 3 support is not in a stable release yet. I'm doing some more work on it so I can release it on PyPI. Have you tried master with success?

**Comment by 5nizza** [comment]
yes, on master python3 seems to work. thanks!

**Comment by tobami** [comment]
Cool, thanks for confirming!
