### ISSUE TITLE
Show min/max result info

### ISSUE THREAD

**Issue by tobami** [tobami/codespeed#2]
The overview table, and the timeline plots should show min/max information when available

**Comment by str4d** [comment]
The timeline plots show min/max info in the tooltips, and extrema bands, for median benchmarks as of #203. Per https://github.com/tobami/codespeed/pull/203#issuecomment-225005324 the next step would be to extend this to mean benchmarks.

**Comment by tobami** [comment]
min max is shown so we can close this issue. Thanks for noticing!
