### ISSUE TITLE
docs: weird rendering of results section in "intro.md"

### ISSUE THREAD

**Issue by Quasilyte** [tobami/codespeed#235]
The [intro.md/results](https://github.com/tobami/codespeed/blob/master/documentation/intro.wiki#results) most likely has different rendering from what author was expecting.

The `**` are used for some kind of emphasis (was **bold** style expected?), which has different purpose in `wiki` language.

See attached screenshot.

![bad_wiki_markdown](https://user-images.githubusercontent.com/6286655/36024630-60de8192-0da1-11e8-985b-e87b1e8624ae.png)

I believe that `**` should be replaced with `'''` to get proper bold text.

**Comment by Quasilyte** [comment]
Maybe `//word//` should be *italic*, but I am not sure. This is why only `**` are changed.

**Comment by Quasilyte** [comment]
The https://github.com/tobami/codespeed/wiki/Overview has proper content, so I guess this issue is irrelevant.

**Comment by tobami** [comment]
@Quasilyte it does look badly rendered when browsing the file on github, but as you said the actual wiki (which is the purpose the file was created for), does render properly.
