### ISSUE TITLE
commits/git: add_json_results executes N "git pull" commands, where N is the number of new revisions

### ISSUE THREAD

**Issue by quasilyte** [tobami/codespeed#237]
In my current experience, enabling project repository `kind=git` makes `save_result` function
call `commits.get_logs` with `update=True` for each result entry that references
revision that is not present in the database.

Ordinary save_result for 1 item (no VCS integration) takes `~50ms`.
With `git` enabled, it's `15.2s`.
For two items it's `100ms` vs `30s` (each additional revision makes things annoyingly slower).

I believe that `git pull` can be either executed once, in the beginning of `add_json_results`,
or for each commit hash miss (when working tree has no specified commit).
One of the problematic places is unconditional `update=True` in `save_result`:
```py
commit_logs = commits.get_logs(rev, rev, update=True)
```

Note that this happens only for new commits.
This, however, can happen in at least three scenarios:
1. Collecting historical data. This may result in thousands new revisions. Especially if this data is intended to be discarded after analysis.
2. Active development phase where you can truncate data sometimes. The instant to "dozens of seconds" slowdown makes difference.
3. Adding new project that have many commits (none of them are stored in DB).

This is not critical, but not so hard to fix issue.
Though it may be more tricky than I see it right now.
I can try proposing a PR with fix if described case is confirmed as issue.

**Comment by tobami** [comment]
That's a very thorough description of the problem!

TBH even the 15s for one item is worrying. How bit is the repo you are
using?

In any case I think it makes total sense to do the optimization you
suggest, I'll happily review that.

**Comment by Quasilyte** [comment]
```bash
$ time git pull
Already up-to-date.

real	0m13.600s
user	0m0.340s
sys	0m0.084s
```

```bash
$ git remote get-url origin
https://go.googlesource.com/go
```
It is possible to try github mirror, but this has it's own disadvantages.
(Own mirror is an option, but for my situation this can't be done in near future.)

If `git pull` executed like 1 time, then single pull time is not that significant when using batch result insertion.

**Comment by tobami** [comment]
OK, let's do single pull time
