### ISSUE TITLE
timeline/changes: blank page for testdata

### ISSUE THREAD

**Issue by Quasilyte** [tobami/codespeed#238]
**Timeline** and **changes** show no data for testdata.
The message is "No data found" for **changes** and "No data found for the selected options"
for **timeline**.

Steps to reproduce:
1. Get codespeed tip version (master branch).
2. Run migrations `python manage.py migrate`.
3. Load test data `./manage.py loaddata codespeed/fixtures/testdata.json`.
4. Run server and visit timeline/changes page.

Encountered this on my data, then checked out https://github.com/tobami/codespeed/issues/142
which recommended `DEF_BRANCH='master'` (I am using "git" repo type and default branch is master).
Also tried to use "default" branch everywhere -- no result.

Testdata should be more representative and enable codespeed exploration (right now it does not help in figuring out what is wrong with my database because there is no way to compare it with proper example).

I will try other codespeed revisions, latest release, for example, and report results here.

**Comment by tobami** [comment]
After the def branch (per project) refactor, some of the test data might not be uptodate any more. We'll have to update that.

**Comment by Quasilyte** [comment]
Could you please explain what changes may be required to achieve minimum version that results in non-blank timelines and changes?
Thank you.

**Comment by tobami** [comment]
`DEF_BRANCH` is no longer used (see how it's no longer explained in the readme). Instead, each project in the database sets its own value, that way you can have projects with different version control systems.

All that's needed is probably to add a value for the field `default_branch` to the projects in the testdata.json file:
https://github.com/tobami/codespeed/blob/master/codespeed/fixtures/testdata.json#L4

**Comment by Quasilyte** [comment]
@tobami, this was the case. Thank you for quick response.

**Comment by tobami** [comment]
It's quite important actually to have a meaningful test dataset to be able to see how Codespeed works and what it provides. I'm sure it can be improved further.

In any case great that is works now.
