### ISSUE TITLE
run_gunicorn does not work

### ISSUE THREAD

**Issue by Timmmm** [tobami/codespeed#247]
I followed the instructions in the sample project readme for nginx and gunicorn, but just get to here:

```
# python3 manage.py run_gunicorn
Unknown command: 'run_gunicorn'
Type 'manage.py help' for usage.
```

**Comment by Emil-G** [comment]
Yes, sample_config does not seem to be updated. PR here, to add the new format: https://github.com/tobami/codespeed/pull/257
