### ISSUE TITLE
Performance of Timeline View with large numbers of Benchmarks

### ISSUE THREAD

**Issue by smarr** [tobami/codespeed#254]
Hi:

I wanted to ask for advise on how I could possibly improve the performance of the timeline view when having about a hundred benchmarks and multiple executables (see http://somns-speed.stefan-marr.de/timeline/).

Currently, the option to display all in a grid just takes ages, or times out. With this I mean response time is in the range of minutes.

I started looking at the loop here:
https://github.com/tobami/codespeed/blob/master/codespeed/views.py#L287

But can't really imagine a solution that would give better performance.
Though, I haven't really tried any variations yet. Just thought about how this could be possibly expressed in SQL.
I had hoped that it's possible to turn the loop over the executables into a single query, but I don't think this is really practical. I am also not sure my sqlite database would cope much better with it.

So, I was thinking, perhaps there is a way of streaming the results to the client, which can then gradually display them?
Though, I have no idea how this would fit into Django.

Any suggests or comments welcome.

Thank you
Stefan

**Comment by tobami** [comment]
Indeed this case is not easy to optimize on a normal SQL database/schema. We are talking dozens of different data series, multiple executables and many dozens of data points each. On that scale the data has to be structured differently or even on a different data store.

That is not to say that this view cannot be optimized a bit more.
Or, similar to what you suggest of streaming,  the results could be fetched benchmark by benchmark in separate ajax calls, and the `gettimelinedata` view would be simplified to not look at the special "benchmark" `grid`.
