### ISSUE TITLE
Add security measures for POSTing

### ISSUE THREAD

**Issue by tobami** [tobami/codespeed#34]
Currently anyone can POST data to a Codespeed instance. Some kind of security is needed. Either proper authentication or a simpler secret key.

**Comment by vitaut** [comment]
I couldn't find any reference to an authentication mechanism in Codespeed other than two closed issues, this and #145. Is it supported now?

**Comment by tobami** [comment]
The API-based implementation was removed due to the committer not resolving all problems. So no, there is no authentication yet.

**Comment by vitaut** [comment]
I see. Is there any other way to limit POSTing to Codespeed?

**Comment by tobami** [comment]
Currently not. I plan to look into it next though.

**Comment by vitaut** [comment]
Great, thanks.

**Comment by mwatts15** [comment]
I believe the issue reference should be #146.
